'use client';

import * as React from 'react';
import {
  Keyboard,
  Music,
  OctagonX,
  Volume2,
  VolumeX,
  Sparkles,
  Loader,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { useSound, type InstrumentName } from '@/hooks/use-sound';
import { Piano } from '@/components/piano';
import { HarmonySuggester } from '@/components/harmony-suggester';
import { Sketchbook, type TranscriptEntry, type SketchbookRow } from '@/components/sketchbook';
import { KEYBOARD_MAPPING, INSTRUMENTS, KEY_NOTES, NOTES } from '@/lib/constants';
import { TYPICAL_PROGRESSIONS, COMMON_OTHER_CHORDS } from '@/lib/constants';
import { Logo } from '@/components/icons';
import { cn } from '@/lib/utils';
import type { SuggestHarmonyOutput, Chord } from '@/ai/flows/suggest-harmony';
// ADD THESE HELPER FUNCTIONS AFTER YOUR IMPORTS

const ALL_NOTES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];

/**
 * Builds a Dominant 7th chord from a root note.
 */
function getDominant7thChord(rootNote: string): Chord {
  const rootIndex = ALL_NOTES.indexOf(rootNote);
  if (rootIndex === -1) {
    return { name: 'Error', notes: [] };
  }
  const third = ALL_NOTES[(rootIndex + 4) % 12];
  const fifth = ALL_NOTES[(rootIndex + 7) % 12];
  const seventh = ALL_NOTES[(rootIndex + 10) % 12];
  return {
    name: `${rootNote}7`,
    notes: [rootNote, third, fifth, seventh],
  };
}
export default function Home() {
  const [octave, setOctave] = React.useState(4);
  const [activeNotes, setActiveNotes] = React.useState<string[]>([]);
  const [pianoKey, setPianoKey] = React.useState<string>('C Major');
  // State to hold the chord progression generated by AI, overrides default if not null
  const [aiChordProgression, setAiChordProgression] = React.useState<Chord[] | null>(null);
  const [sketchbookRows, setSketchbookRows] = React.useState<SketchbookRow[]>([{ id: 0, entries: [] }]);
  const entryIdCounter = React.useRef(0);
  const rowIdCounter = React.useRef(1);

  const {
    isLoaded,
    isMuted,
    playNote,
    stopNote,
    playChord,
    playNoteWithDuration,
    setInstrument,
    toggleMute,
    initializeAudio,
  } = useSound();
  const [audioInitialized, setAudioInitialized] = React.useState(false);
  const notesInKey = pianoKey ? KEY_NOTES[pianoKey] : null;
  // State to track the selected chord progression by name
  const [selectedProgressionName, setSelectedProgressionName] = React.useState<string | null>(null);


  // Function to get the note from the key notes array based on degree
  const getNoteFromDegree = React.useCallback((degree: number, keyNotes: string[]): string | undefined => {
      // Degrees are 1-based, array indices are 0-based
      return keyNotes[degree - 1];
  }, []);

  // Function to generate a major triad based on a root note
  const getMajorTriad = React.useCallback((root: string, keyNotes: string[]): string[] | undefined => {
    const rootIndexInKey = keyNotes.indexOf(root);
    if (rootIndexInKey === -1) return undefined;

    const third = keyNotes[(rootIndexInKey + 2) % keyNotes.length];
    const fifth = keyNotes[(rootIndexInKey + 4) % keyNotes.length];

    return [root, third, fifth];
  }, []);

    // Function to generate a minor triad based on a root note
  const getMinorTriad = React.useCallback((root: string, keyNotes: string[]): string[] | undefined => {
    const rootIndexInKey = keyNotes.indexOf(root);
    if (rootIndexInKey === -1) return undefined;

    // Minor triad is root, minor 3rd, perfect 5th. In a major key, the ii, iii, vi are minor
    // The notes are still derived from the major key scale degrees relative to the root of the chord

    const third = NOTES[(NOTES.indexOf(root) + 3) % NOTES.length]; // Minor 3rd interval
    const fifth = NOTES[(NOTES.indexOf(root) + 7) % NOTES.length]; // Perfect 5th interval

    // Ensure the notes are within the available NOTES array
      if (NOTES.includes(root) && NOTES.includes(third) && NOTES.includes(fifth)) {
        return [root, third, fifth];
      }
      return undefined;

  }, []);

    // Function to generate a diminished triad based on a root note
    const getDiminishedTriad = React.useCallback((root: string): string[] | undefined => {
        const rootIndex = NOTES.indexOf(root);
        if (rootIndex === -1) return undefined;
        const third = NOTES[(rootIndex + 3) % NOTES.length]; // Minor 3rd
        const fifth = NOTES[(rootIndex + 6) % NOTES.length]; // Diminished 5th
        if (NOTES.includes(root) && NOTES.includes(third) && NOTES.includes(fifth)) {
              return [root, third, fifth];
        }
        return undefined;
    }, []);

  // Function to calculate default chord progressions based on the selected key
  // REPLACE your existing calculateDefaultChordProgressions with this one

const calculateDefaultChordProgressions = React.useCallback((key: string) => {
  const progressions: { name: string; chords: Chord[] }[] = [];
  const otherChords: Chord[] = [];
  const notes = KEY_NOTES[key];
  if (!notes) return { progressions: [], otherChords: [] };

  const ROMAN_TO_DEGREE: { [key: string]: number } = { 'i': 1, 'ii': 2, 'iii': 3, 'iv': 4, 'v': 5, 'vi': 6, 'vii': 7 };

  // Helper to get chord notes from Roman numeral
  const getChordFromRoman = (roman: string): Chord | undefined => {
    // Check for Secondary Dominant (e.g., "V7/V")
    if (roman.includes('/')) {
      const parts = roman.split('/'); // e.g., ["V7", "V"]
      const targetRoman = parts[1].toLowerCase(); // "v"
      const targetDegree = ROMAN_TO_DEGREE[targetRoman];
      if (!targetDegree) return undefined;

      const targetRoot = notes[targetDegree - 1];

      // The root of the secondary dominant is a perfect fifth (7 semitones) above the target
      const targetRootIndex = ALL_NOTES.indexOf(targetRoot);
      const dominantRootNote = ALL_NOTES[(targetRootIndex + 7) % 12];
      
      // For now, we assume all secondary dominants are V7 chords
      return getDominant7thChord(dominantRootNote);
    }

    // --- Original Diatonic Chord Logic (with slight improvements) ---
    const degreeMatch = roman.match(/^([iIvV]+)/);
    if (!degreeMatch) return undefined;
    
    const degreeRoman = degreeMatch[1];
    const degree = ROMAN_TO_DEGREE[degreeRoman.toLowerCase()];
    if (!degree) return undefined;

    const rootNote = notes[degree - 1];
    if (!rootNote) return undefined;

    let chordNotes: string[] = [];
    let chordName = rootNote;
    const rootIndex = NOTES.indexOf(rootNote);

    if (degreeRoman === 'I' || degreeRoman === 'IV' || degreeRoman === 'V') {
      // Major triad
      chordNotes = [rootNote, NOTES[(rootIndex + 4) % NOTES.length], NOTES[(rootIndex + 7) % NOTES.length]];
    } else if (degreeRoman === 'ii' || degreeRoman === 'iii' || degreeRoman === 'vi') {
      // minor triad
      chordNotes = [rootNote, NOTES[(rootIndex + 3) % NOTES.length], NOTES[(rootIndex + 7) % NOTES.length]];
      chordName += 'm';
    } else if (degreeRoman.toLowerCase() === 'vii') {
      // diminished triad
      chordNotes = [rootNote, NOTES[(rootIndex + 3) % NOTES.length], NOTES[(rootIndex + 6) % NOTES.length]];
      chordName += '°';
    }

    if (chordNotes.length > 0) {
      return { name: chordName, notes: chordNotes };
    }
    return undefined;
  };

  // Generate Typical Progressions
  for (const progDef of TYPICAL_PROGRESSIONS) {
    const chords: Chord[] = [];
    for (const roman of progDef.romanNumerals) {
      const chord = getChordFromRoman(roman);
      if (chord) {
        chords.push(chord);
      }
    }
    if (chords.length > 0) {
      progressions.push({ name: progDef.name, chords });
    }
  }

  // Generate Other Common Chords
  for (const roman of COMMON_OTHER_CHORDS) {
    const chord = getChordFromRoman(roman);
      if (chord) {
        otherChords.push(chord);
      }
  }

  return { progressions, otherChords };
}, []);

  const handleInitializeAudio = React.useCallback(async () => {
    await initializeAudio();
    setAudioInitialized(true);
  }, [initializeAudio]);

  // Function to add an entry to the sketchbook transcript
  const addTranscriptEntry = React.useCallback((content: string, type: 'note' | 'chord') => {
    setSketchbookRows(prevRows => {
      const newEntry: TranscriptEntry = { id: entryIdCounter.current++, content, type };
      const lastRow = prevRows[prevRows.length - 1];
      const updatedLastRow = {
        ...lastRow,
        entries: [...lastRow.entries, newEntry],
      };
      return [...prevRows.slice(0, -1), updatedLastRow];
    });
  }, []);
  
  // Function to add a new row to the sketchbook
  const handleAddRow = React.useCallback(() => {
    setSketchbookRows(prev => [...prev, { id: rowIdCounter.current++, entries: [] }]);
  }, []);
  

  const handleClearEntry = React.useCallback((rowId: number, entryId: number) => {
    setSketchbookRows(prevRows =>
      prevRows.map(row =>
        row.id === rowId
          ? { ...row, entries: row.entries.filter(entry => entry.id !== entryId) }
          : row
      )
    );
  }, []);
  

  const handleClearAllEntries = React.useCallback(() => {
    setSketchbookRows([{ id: 0, entries: [] }]);
    rowIdCounter.current = 1;
    entryIdCounter.current = 0;
  }, []);

  const handleChordPlay = React.useCallback((chord: Chord, addToTranscript = true) => {
    if (!chord.notes || chord.notes.length === 0) return;
  
    if (addToTranscript) {
      addTranscriptEntry(chord.name, 'chord');
    }

    const rootNote = chord.notes[0];
    const rootIndex = NOTES.indexOf(rootNote);
  
    const notesToPlay = chord.notes.map(note => {
      const noteIndex = NOTES.indexOf(note);
      // If note comes before root note in the scale array, it's in the next octave up
      const currentOctave = noteIndex < rootIndex ? octave + 1 : octave;
      return `${note}${currentOctave}`;
    });
  
    playChord(notesToPlay, '1s');
  
    // Highlight notes on the piano
    setActiveNotes(prev => [...prev, ...notesToPlay]);
  
    // Un-highlight notes after they finished playing
    setTimeout(() => {
      setActiveNotes(prev => prev.filter(n => !notesToPlay.includes(n)));
    }, 1000);

  }, [addTranscriptEntry, octave, playChord]);

  const handlePlayEntry = React.useCallback((entry: TranscriptEntry) => {
    if (entry.type === 'note') {
      playNoteWithDuration(entry.content, '8n');
      setActiveNotes(prev => [...prev, entry.content]);
      setTimeout(() => {
        setActiveNotes(prev => prev.filter(n => n !== entry.content));
      }, 500);
    } 
      else if (entry.type === 'chord') {
      // Find the chord in either the AI progression or the default progressions
      let matchedChord = aiChordProgression?.find(c => c.name === entry.content);
      if (!matchedChord) {
          // If not found in AI progression, search in default progressions
          const defaultProgs = calculateDefaultChordProgressions(pianoKey);
          matchedChord = defaultProgs.otherChords.find(c => c.name === entry.content);
          // If still not found, search in the specific default progressions
          if (!matchedChord) {
              for (const prog of defaultProgs.progressions) {
                  // Check all default progressions, not just the currently selected one for playback
                  matchedChord = prog.chords.find(c => c.name === entry.content);
                  if (matchedChord) break;
              }
          }
        }
      if (matchedChord) {
        handleChordPlay(matchedChord, false); // Don't add to transcript again
      }
    }

  }, [aiChordProgression, calculateDefaultChordProgressions, pianoKey, handleChordPlay, playNoteWithDuration]);

  // Calculate default progressions whenever pianoKey changes
  const defaultChordProgressions = React.useMemo(() => {
      return calculateDefaultChordProgressions(pianoKey);
  }, [pianoKey, calculateDefaultChordProgressions]);

  // Update selected progression when default progressions change (e.g., key change)
  React.useEffect(() => {
    if (defaultChordProgressions.progressions.length > 0) {
        setSelectedProgressionName(defaultChordProgressions.progressions[0].name);
    } else {
        setSelectedProgressionName(null);
    }
  }, [defaultChordProgressions.progressions]);

  // Determine which chord progression to display: AI overrides default if available
  const displayedChordProgressions = aiChordProgression
    ? { progressions: [{ name: 'AI Suggestion', chords: aiChordProgression }], otherChords: [] } // Wrap AI chords in a progression-like structure for display
    : defaultChordProgressions;


  if (!audioInitialized) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen bg-background text-center p-4">
        <Logo className="w-24 h-24 text-primary mb-6" />
        <h1 className="text-4xl font-headline mb-2">Welcome to Keyboard Sketchbook</h1>
        <p className="text-lg text-muted-foreground mb-8 max-w-2xl">
          An immersive musical experience for exploring sacred harmonies. Click below to enable audio and begin your composition.
        </p>
        <Button onClick={handleInitializeAudio} size="lg" className="bg-accent text-accent-foreground hover:bg-accent/90">
          <Volume2 className="mr-2 h-5 w-5" />
          Enable Audio
        </Button>
      </div>
    );
  }

  if (!isLoaded) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen bg-background text-center">
        <Loader className="h-12 w-12 animate-spin text-primary" />
        <p className="text-muted-foreground mt-4">Loading Instruments...</p>
      </div>
    );
  }

  return (
    <main className="min-h-screen bg-background text-foreground p-4 lg:p-8">
      <div className="grid grid-cols-1 xl:grid-cols-12 gap-6 max-w-screen-2xl mx-auto">
        <header className="xl:col-span-12 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Logo className="w-10 h-10 text-primary" />
            <div>
              <h1 className="text-2xl font-bold font-headline">Keyboard Sketchbook</h1>
              <p className="text-sm text-muted-foreground">A tool for musical exploration</p>
            </div>
          </div>
          <Button onClick={toggleMute} variant="ghost" size="icon">
            {isMuted ? <VolumeX /> : <Volume2 />}
            <span className="sr-only">Toggle Mute</span>
          </Button>
        </header>

        <div className="xl:col-span-8 flex flex-col gap-6">
          {pianoKey && notesInKey && (
            <Card>
              <CardHeader className="pb-2">
                <CardTitle>Active Key: {pianoKey}</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground">
                  The following notes are in this key:{" "}
                  <span className="font-mono text-foreground tracking-wider">{notesInKey.join(', ')}</span>
                </p>
              </CardContent>
            </Card>
          )}
          
          {displayedChordProgressions && displayedChordProgressions.progressions.length > 0 && !aiChordProgression && (
              <div>
                  <label className="text-sm font-medium mb-2 block">Select Chord Progression</label>
                  <Select onValueChange={setSelectedProgressionName} value={selectedProgressionName || ''}>
                      <SelectTrigger>
                          <SelectValue placeholder="Select a progression" />
                      </SelectTrigger>
                      <SelectContent>
                          {displayedChordProgressions.progressions.map((prog) => (
                              <SelectItem key={prog.name} value={prog.name}>
                                  {prog.name}
                              </SelectItem>
                          ))}
                      </SelectContent>
                  </Select>
              </div>
          )}
          
          {/***************************************************************}
          {* THIS IS THE CORRECTED SECTION                               *}
          {/***************************************************************/}
          <Card>
            <CardHeader>
              <CardTitle>Chord Progression Player</CardTitle>
              <CardDescription>Click a chord to hear it played.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Case 1: Display AI-Generated Progression */}
              {aiChordProgression ? (
                <div className="w-full">
                  <h4 className="text-sm font-semibold mb-2">AI Suggestion</h4>
                  <div className="flex flex-wrap gap-2">
                    {aiChordProgression.map((chord, index) => (
                      <Button
                        key={`ai-chord-${index}`}
                        variant="outline"
                        onClick={() => handleChordPlay(chord)}
                      >
                        {chord.name}
                      </Button>
                    ))}
                  </div>
                </div>
              ) : null}

              {/* Case 2: Display Selected Default Progression (only if no AI progression) */}
              {selectedProgressionName && !aiChordProgression ? (
                displayedChordProgressions.progressions
                  .filter(prog => prog.name === selectedProgressionName)
                  .map(prog => (
                    <div key={prog.name} className="w-full">
                      <h4 className="text-sm font-semibold mb-2">{prog.name}</h4>
                      <div className="flex flex-wrap gap-2">
                        {prog.chords.map((chord, index) => (
                          <Button
                            key={`${prog.name}-${chord.name}-${index}`}
                            variant="outline"
                            onClick={() => handleChordPlay(chord)}
                          >
                            {chord.name}
                          </Button>
                        ))}
                      </div>
                    </div>
                  ))
              ) : null}

              {/* Case 3: Display Other Common Chords (always shows if they exist) */}
              {displayedChordProgressions.otherChords.length > 0 && (
                <div className="w-full">
                  <h4 className="text-sm font-semibold mb-2">Other Common Chords</h4>
                  <div className="flex flex-wrap gap-2">
                    {displayedChordProgressions.otherChords.map((chord, index) => (
                      <Button
                        key={`other-chord-${index}`}
                        variant="outline"
                        onClick={() => handleChordPlay(chord)}
                      >
                        {chord.name}
                      </Button>
                    ))}
                  </div>
                </div>
              )}
            </CardContent>
          </Card>

          <Sketchbook 
            rows={sketchbookRows}
            onClearEntry={handleClearEntry}
            onClearAll={handleClearAllEntries}
            onAddRow={handleAddRow}
            onPlayEntry={handlePlayEntry}
          />

          <Card className="rounded-xl overflow-hidden shadow-lg border-2 border-border">
            <CardContent className="p-4 md:p-6">
              <Piano
                octave={octave}
                playNote={playNote}
                stopNote={stopNote}
                activeNotes={activeNotes}
                setActiveNotes={setActiveNotes}
                notesInKey={notesInKey}
                onNotePlay={addTranscriptEntry}
              />
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2"><Keyboard /> Keyboard Mapping</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex flex-wrap gap-x-6 gap-y-2 text-sm text-muted-foreground">
                {Object.entries(KEYBOARD_MAPPING).map(([key, note]) => (
                  <div key={key} className="flex items-center gap-2">
                    <span className="font-mono bg-muted px-2 py-1 rounded-md">{key.toUpperCase()}</span>
                    <span>-&gt;</span>
                    <span className="font-semibold">{note}</span>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="xl:col-span-4 flex flex-col gap-6">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2"><Music /> Controls</CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div>
                <label className="text-sm font-medium mb-2 block">Instrument</label>
                <Select
                  defaultValue="piano"
                  onValueChange={(value: InstrumentName) => setInstrument(value)}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select an instrument" />
                  </SelectTrigger>
                  <SelectContent>
                    {INSTRUMENTS.map((inst) => (
                      <SelectItem key={inst.value} value={inst.value}>
                        {inst.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div>
                <label className="text-sm font-medium mb-2 block">Octave</label>
                <div className="flex items-center gap-2">
                  <Button
                    onClick={() => setOctave((o) => Math.max(0, o - 1))}
                    disabled={octave === 0}
                    variant="outline"
                  >
                    -
                  </Button>
                  <span className="font-mono text-lg w-12 text-center">{octave}</span>
                  <Button
                    onClick={() => setOctave((o) => Math.min(8, o + 1))}
                    disabled={octave === 8}
                    variant="outline"
                  >
                    +
                  </Button>
                </div>
              </div>
              
              <div>
                <label className="text-sm font-medium mb-2 block">Selected Key</label>
                <Select onValueChange={setPianoKey} value={pianoKey}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select a key" />
                  </SelectTrigger>
                  <SelectContent>
                    {Object.keys(KEY_NOTES).map((key) => (
                      <SelectItem key={key} value={key}>
                        {key}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2"><Sparkles className="text-accent"/> AI Harmony Helper</CardTitle>
              <CardDescription>Get AI-powered chord & harmony suggestions.</CardDescription>
            </CardHeader>
            <CardContent>
              <HarmonySuggester onChordProgressionChange={setAiChordProgression} selectedKey={pianoKey} onKeyChange={setPianoKey} />
            </CardContent>
          </Card>
        </div>
      </div>
    </main>
  );
}
